export enum CalendarEventTypeEnum {
    SEMINAR = 'SEMINAR',
    EVENT = 'EVENT',
    INITIAL_TRAINING = 'INITIAL_TRAINING',
    TRAINING = 'TRAINING',
    CONFERENCE = 'CONFERENCE',
    INTERNAL_MEETING = 'INTERNAL_MEETING',
    EXTERNAL_MEETING = 'EXTERNAL_MEETING'
}
