export enum ExamAttendeeEnum {
    ACCEPTED_INVITATION = "ACCEPTED_INVITATION",
    EXAM_FAILED = "EXAM_FAILED",
    EXAM_PASSED = "EXAM_PASSED",
    EXAM_PAUSED = "EXAM_PAUSED",
    EXAM_STARTED = "EXAM_STARTED",
    INVITATION_SENT = "INVITATION_SENT"
}
