export enum FileUploadEntityEnum {
    ATTENDEE_CERT_TEMPLATE = "ATTENDEE_CERT_TEMPLATE",
    BIRT_REPORT_DEFINITION = "BIRT_REPORT_DEFINITION",
    EBOOK = "EBOOK",
    EXAM_MATERIAL = "EXAM_MATERIAL",
    LECTURER_CERT_TEMPLATE = "LECTURER_CERT_TEMPLATE",
    LECTURE_MATERIAL = "LECTURE_MATERIAL",
    SEMINAR_INVITATION = "SEMINAR_INVITATION",
    SEMINAR_AGENDA = "SEMINAR_AGENDA",
    SEMINAR_EVALUATION_REPORT = "SEMINAR_EVALUATION_REPORT",
    SEMINAR_POZIV_SUDOVIMA = "SEMINAR_POZIV_SUDOVIMA",
    SEMINAR_MATERIAL = "SEMINAR_MATERIAL",
    SEMINAR_CONTRACT = "SEMINAR_CONTRACT",
    SEMINAR_COST = "SEMINAR_COST",
    USER_PROFILE = 'USER_PROFILE',
    USER_CONTRACT = "USER_CONTRACT"
}
