export enum QuestionTypeEnum {
    SINGLE_CHOICE = "SINGLE_CHOICE",
    MULTIPLE_CHOICE = "MULTIPLE_CHOICE",
    OPEN_ENDED = "OPEN_ENDED",
    CROSSTAB = "CROSSTAB",
    CLASSIC_CROSSTAB = "CLASSIC_CROSSTAB",
    INFOBOX = "INFOBOX",
}
