export enum DataGridCellTypeEnum {
  TEXT = "TEXT",
  NUMBER = "NUMBER",
  CHECKBOX = "CHECKBOX",
  OPTION = "OPTION",
  MULTIOPTION = "MULTIOPTION",
  DATE = "DATE",
  TEXTAREA = "TEXTAREA",
  RANGE = "RANGE"
}
